export const FOCUS = "focus"
export const HIGHLIGHT = "highlight"
export const CHANGEDATA = "changedata"
export const CHANGEMODE = "changemode"
export const AZOPTION = "azoption"
export const PODOPTION = "podoption"
export const ROLEOPTION = "roleoption"
export const LINKOPTION = "linkoption"

export const DEFAULT = "DEFAULTVALUE"